In [3]:
from tensorflow.keras.preprocessing.text import one_hot

In [4]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [38]:
# define vocabulary size -- for index size
voc_size=10000

In [39]:
# one hot encoding
one_hot_repr=[one_hot(words,voc_size) for words in sent]
one_hot_repr

# around 10000 indexes, words are distributed.
# below output is the occurence of word at that index is 1 and remaning places for 10000 index all are zeros


[[7976, 6133, 4970, 7950],
 [7976, 6133, 4970, 9344],
 [7976, 6743, 4970, 304],
 [5526, 6146, 6948, 4616, 7869],
 [5526, 6146, 6948, 4616, 2987],
 [9422, 7976, 9716, 4970, 5845],
 [6284, 994, 3622, 4616]]

In [40]:
# word embedding representation
from tensorflow.keras.layers import Embedding
# from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential


In [41]:
import numpy as np

In [42]:
sent_length=8
# make every sentences length equal in size. So we do pre_pading
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
embedded_docs

array([[   0,    0,    0,    0, 7976, 6133, 4970, 7950],
       [   0,    0,    0,    0, 7976, 6133, 4970, 9344],
       [   0,    0,    0,    0, 7976, 6743, 4970,  304],
       [   0,    0,    0, 5526, 6146, 6948, 4616, 7869],
       [   0,    0,    0, 5526, 6146, 6948, 4616, 2987],
       [   0,    0,    0, 9422, 7976, 9716, 4970, 5845],
       [   0,    0,    0,    0, 6284,  994, 3622, 4616]])

In [43]:
# feature representation
dim=10

In [44]:
model=Sequential()
model.add(Embedding(voc_size, dim, input_length=sent_length))
model.compile('adam','mse')

In [45]:
model.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_3 (Embedding)     (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [46]:
model.predict(embedded_docs)

1/1 [==============================] - 2s 2s/step


array([[[ 0.01459149,  0.03810597,  0.03469551, -0.02286514,
          0.02264348,  0.00713431, -0.0170575 , -0.04660649,
          0.00419803,  0.0214368 ],
        [ 0.01459149,  0.03810597,  0.03469551, -0.02286514,
          0.02264348,  0.00713431, -0.0170575 , -0.04660649,
          0.00419803,  0.0214368 ],
        [ 0.01459149,  0.03810597,  0.03469551, -0.02286514,
          0.02264348,  0.00713431, -0.0170575 , -0.04660649,
          0.00419803,  0.0214368 ],
        [ 0.01459149,  0.03810597,  0.03469551, -0.02286514,
          0.02264348,  0.00713431, -0.0170575 , -0.04660649,
          0.00419803,  0.0214368 ],
        [-0.04553703,  0.02768217, -0.00378182,  0.01446551,
         -0.03233486,  0.0228512 , -0.03342487, -0.01927616,
         -0.01106077,  0.03877522],
        [-0.02446361,  0.02671032, -0.01924065,  0.0127792 ,
          0.00373453,  0.01754948, -0.03382923, -0.04770318,
         -0.04879419, -0.02503965],
        [-0.03402792, -0.01099472, -0.00895587,  0.0

In [47]:
embedded_docs[0]

array([   0,    0,    0,    0, 7976, 6133, 4970, 7950])

In [48]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 48ms/step


array([[ 0.01459149,  0.03810597,  0.03469551, -0.02286514,  0.02264348,
         0.00713431, -0.0170575 , -0.04660649,  0.00419803,  0.0214368 ],
       [ 0.01459149,  0.03810597,  0.03469551, -0.02286514,  0.02264348,
         0.00713431, -0.0170575 , -0.04660649,  0.00419803,  0.0214368 ],
       [ 0.01459149,  0.03810597,  0.03469551, -0.02286514,  0.02264348,
         0.00713431, -0.0170575 , -0.04660649,  0.00419803,  0.0214368 ],
       [ 0.01459149,  0.03810597,  0.03469551, -0.02286514,  0.02264348,
         0.00713431, -0.0170575 , -0.04660649,  0.00419803,  0.0214368 ],
       [-0.04553703,  0.02768217, -0.00378182,  0.01446551, -0.03233486,
         0.0228512 , -0.03342487, -0.01927616, -0.01106077,  0.03877522],
       [-0.02446361,  0.02671032, -0.01924065,  0.0127792 ,  0.00373453,
         0.01754948, -0.03382923, -0.04770318, -0.04879419, -0.02503965],
       [-0.03402792, -0.01099472, -0.00895587,  0.02374646,  0.03975281,
         0.01295206, -0.03126607,  0.030148  